# Generated by Django 4.0.2 on 2022-02-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_foto'),
        ('contatos', '0004_contato_foto'),
    ]

    operations = [
    ]
